---
# Github action that runs on module release to create files like
# Update JSON, CHANGELOG, ...

name: Generate update JSON and release module

on:
  push:
    branches:
      - "*"

jobs:
  get_vars:
    name: Get module variables from "module.prop" and "config.prop"
    runs-on: ubuntu-latest
    outputs:
      # Module.prop variables
      id: ${{ steps.collect.outputs.id }}
      name: ${{ steps.collect.outputs.name }}
      version: ${{ steps.collect.outputs.version }}
      versionCode: ${{ steps.collect.outputs.versionCode }}
      author: ${{ steps.collect.outputs.author }}
      description: ${{ steps.collect.outputs.description }}

      # Config.prop variables
      zip_exclude: ${{ steps.collect.outputs.zip_exclude }}
      changelog: ${{ steps.collect.outputs.changelog }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare shell
        run: chmod 777 ./.github/bin/*

      - name: Get variables
        run: ./.github/bin/variables.sh >> "${GITHUB_OUTPUT}"
        id: collect

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Prepare shell
        run: chmod 777 ./.github/bin/*

      - name: Get variables
        run: ./.github/bin/variables.sh >> "${GITHUB_ENV}"

      - name: Create module ZIP
        run: ./.github/bin/createZip.sh ${{ env.zipname }} ${{ env.version }} ${{ env.zip_exclude }} >> "${GITHUB_ENV}"

      - name: Add update JSON to module.prop
        run: ./.github/bin/refineModule.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.changelog }}
            ${{ env.zipname }}
            update.json

      - name: Generate update JSON
        run: ./.github/bin/updateJson.sh ${{ env.version }} ${{ env.versionCode }} ${{ env.changelog }} ${{ env.zipname }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.changelog }}
            ${{ env.zipname }}
            update.json
